image: docker-gsrt-tech.af.paloaltonetworks.local/base-image/alpine:latest

stages:
    - test
    - build
    - pypi
    - post

before_script:
  - python3 -V

test:
    stage: test
    script:
        - pip install tox flake8 pytest
        - mkdir -p ~/.config
        - echo "$FULL_PANW_CONFIG" > ~/.config/panw
        - tox

pypi:
    stage: pypi
    script:
        - pip3 install -U twine wheel
        - python3 setup.py bdist_wheel
        - twine upload dist/*
    only:
        - master-python3
build-utilties-container:
    stage: post
    trigger:
        project: gsrt-tools/gsrt-utilities-container
        branch: master

build-overwatch-container:
    stage: post
    trigger:
        project: gsrt-tools/gsrt-utilities-container
        branch: master
