# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: registry.gsrt.paloaltonetworks.local:5000/gsrttech/playbooks_base:latest

before_script:
  - python -V               # Print out python version for debugging

test:
  script:
  - pip install tox flake8
  - tox
  
artifactory:
  script:
  - pip install -U twine
  - python3 setup.py sdist
  - twine upload dist/*