image: docker-gsrt-tech.af.paloaltonetworks.local/base-image/alpine:latest

stages:
    - test
    - build
    - pypi

before_script:
  - python3 -V

test:
    stage: test
    script:
        - pip install tox flake8 pytest
        - tox
