image: docker-gsrt-tech.af.paloaltonetworks.local/base-image/gitlabci:latest

stages:
    - test
    - build
    - pypi
    - post

before_script:
  - python3 -V

test:
    stage: test
    script:
        - mkdir -p ~/.config
        - echo "$FULL_PANW_CONFIG" > ~/.config/panw
        - tox

pypi:
    stage: pypi
    script:
        - python3 setup.py bdist_wheel
        - twine upload dist/*
    only:
        refs:
            - master
        changes:
            - "*/version.py"

#build-utilties-container:
#    stage: post
#    trigger:
#        project: gsrt-tools/gsrt-utilities-container
#        branch: master
#    only:
#        refs:
#            - master
#        changes:
#            - "*/version.py"

build-overwatch-container:
    stage: post
    trigger:
        project: gsrt-tools/docker-overwatch
        branch: master
    only:
        refs:
            - master
        changes:
            - "*/version.py"
