image: docker-gsrt-tech.af.paloaltonetworks.local/base-image/alpine:latest

stages:
    - test
    - build
    - pypi

before_script:
  - python3 -V

test:
    stage: test
    script:
        - pip install tox flake8 pytest
        - mkdir ~/.config
        - echo -e "[autofocus]\napikey=${AF_API_KEY}" > ~/.config/panw
        - tox

pypi:
    stage: pypi
    script:
        - pip3 install -U twine wheel
        - python3 setup.py bdist_wheel
        - twine upload dist/*
        # Triger a rebuild of the tools container
        - curl -X POST -F token=bbbd5b8ee425f3ad32a03a91ee4cc9 -F ref=master https://gitlab.gsrt.paloaltonetworks.local/api/v4/projects/54/trigger/pipeline
    only:
        - master-python3

